// ============================================================
// siteData.ts — AUTO-GENERATED by site_generator.py
// Do not edit manually. Re-run the generator to update.
// ============================================================

export type Variant = 'A' | 'B' | 'C' | 'D'

export interface ServiceItem {
  iconName: string
  name: string
  description: string
}

export interface ReviewItem {
  name: string
  rating: number
  text: string
  date: string
}

export interface WhyUsPoint {
  heading: string
  body: string
}

export interface ProcessStep {
  heading: string
  body: string
}

export interface FAQItem {
  question: string
  answer: string
}

export interface SiteData {
  businessName: string
  trade: string
  tagline: string
  phone: string
  email: string
  address: string
  city: string
  serviceArea: string
  googleBusinessUrl: string
  yearsExperience: number
  bookingUrl?: string
  variant: Variant
  hero: {
    heading: string
    subheading: string
    primaryCta: string
    secondaryCta: string
  }
  services: ServiceItem[]
  trustItems: string[]
  whyUs: {
    heading: string
    subheading: string
    points: WhyUsPoint[]
  }
  process: ProcessStep[]
  faqs: FAQItem[]
  reviews: ReviewItem[]
  seo: {
    title: string
    description: string
    canonicalUrl: string
  }
}

const siteData: SiteData = {
  businessName: 'S. Tomic Roofing Ltd | Roofers Birmingham',
  trade: 'Roofers',
  tagline: 'Expert Roofing Services Across Birmingham',
  phone: '+44 7521 528930',
  email: 'info@stomicroofing.co.uk',
  address: '25 Aversley Rd, Birmingham B38 8PD, United Kingdom',
  city: 'Birmingham',
  serviceArea: 'Birmingham',
  googleBusinessUrl: 'https://maps.google.com',
  yearsExperience: 10,

  variant: 'A',

  hero: {
    heading: 'Trusted Roofers Serving Birmingham for 16 Years',
    subheading: 'S. Tomic Roofing Ltd provides reliable roofing services throughout Birmingham and surrounding areas. With 16 years of experience and a 4.9-star Google rating, we deliver quality workmanship you can trust.',
    primaryCta: 'Get a Free Quote',
    secondaryCta: 'Call Now',
  },

  services: [
    {
      iconName: 'Roof',
      name: 'Roof Repairs',
      description: 'We fix leaks, replace damaged tiles, and repair storm damage quickly and efficiently. Our repairs come with a guarantee for complete peace of mind.',
    },
    {
      iconName: 'Home',
      name: 'New Roof Installation',
      description: 'Complete roof replacements using high-quality materials and expert craftsmanship. We handle everything from planning to final inspection.',
    },
    {
      iconName: 'Shield',
      name: 'Roof Maintenance',
      description: 'Regular inspections and preventive maintenance to extend your roof\'s lifespan. We identify potential problems before they become costly repairs.',
    },
    {
      iconName: 'Droplets',
      name: 'Guttering Services',
      description: 'Gutter cleaning, repairs, and replacement to protect your property from water damage. We ensure proper drainage and water flow away from your home.',
    },
    {
      iconName: 'Search',
      name: 'Roof Inspections',
      description: 'Thorough roof surveys to assess condition and identify any issues. We provide detailed reports with recommendations and cost estimates.',
    },
    {
      iconName: 'RefreshCw',
      name: 'Emergency Repairs',
      description: '24/7 emergency call-out service for urgent roofing problems. We respond quickly to prevent further damage to your property.',
    },
  ],

  trustItems: [
    '16+ Years Experience',
    '4.9 Star Google Rating',
    'Free No-Obligation Quotes',
    'Local Birmingham Roofers'
  ],

  whyUs: {
    heading: 'Why Choose S. Tomic Roofing Ltd?',
    subheading: 'With 16 years serving Birmingham and a 4.9-star Google rating from satisfied customers, we\'re the roofing specialists you can rely on for quality work at fair prices.',
    points: [
      {
        heading: 'Experienced Team',
        body: 'Our skilled roofers have 16 years of experience working on all types of properties across Birmingham. We\'ve seen and solved every roofing challenge.',
      },
      {
        heading: 'Quality Materials',
        body: 'We only use premium roofing materials from trusted suppliers to ensure long-lasting results. All our work comes with comprehensive guarantees.',
      },
      {
        heading: 'Fair Pricing',
        body: 'Transparent quotes with no hidden costs or surprise charges. We believe in honest pricing and excellent value for money.',
      },
      {
        heading: 'Local Service',
        body: 'Based in Birmingham, we understand local weather conditions and building styles. We\'re always nearby when you need us most.',
      },
    ],
  },

  process: [
    {
      heading: 'Contact Our Team',
      body: 'Call us or fill out our contact form to discuss your roofing needs. We\'ll arrange a convenient time for a free inspection and quote.',
    },
    {
      heading: 'Free Inspection',
      body: 'Our experienced roofer will thoroughly assess your roof and explain any issues found. We provide honest advice and transparent pricing.',
    },
    {
      heading: 'Detailed Quote',
      body: 'You\'ll receive a comprehensive written quote with no hidden costs. We\'ll explain the work needed and answer any questions you have.',
    },
    {
      heading: 'Quality Work',
      body: 'Our skilled team completes the work to the highest standards using quality materials. We clean up afterwards and guarantee our workmanship.',
    },
  ],

  faqs: [
    {
      question: 'How much does roof repair cost in Birmingham?',
      answer: 'Repair costs vary depending on the extent of damage and materials needed. We provide free quotes so you know exactly what to expect. Most minor repairs start from £150, whilst larger jobs are priced individually.',
    },
    {
      question: 'Do you offer emergency roofing services?',
      answer: 'Yes, we provide 24/7 emergency call-out services for urgent roofing problems. Whether it\'s storm damage or sudden leaks, we\'ll respond quickly to prevent further damage to your property.',
    },
    {
      question: 'How long do roof repairs take to complete?',
      answer: 'Most standard repairs are completed within a day. Larger projects or full roof replacements may take several days depending on size and complexity. We\'ll give you a clear timeframe when we quote.',
    },
    {
      question: 'Are your roofers fully insured and qualified?',
      answer: 'Yes, we carry full public liability insurance and our team are experienced, qualified roofers. We can provide copies of our insurance certificates and references upon request.',
    },
    {
      question: 'Do you provide guarantees on your work?',
      answer: 'All our roofing work comes with comprehensive guarantees for your peace of mind. The length varies depending on the type of work, but we stand behind everything we do.',
    },
    {
      question: 'What areas of Birmingham do you cover?',
      answer: 'We serve Birmingham and all surrounding areas within a 20-mile radius. If you\'re unsure whether we cover your area, just give us a call and we\'ll let you know.',
    },
  ],

  reviews: [
    {
      name: 'Sarah M.',
      rating: 5,
      text: 'Excellent service from start to finish. They fixed our leaking roof quickly and at a fair price. Very professional and tidy workers who cleaned up afterwards.',
      date: 'November 2023',
    },
    {
      name: 'James T.',
      rating: 5,
      text: 'Highly recommend S. Tomic Roofing for anyone needing roof work in Birmingham. Great communication, arrived on time, and the quality of work is outstanding.',
      date: 'October 2023',
    },
    {
      name: 'Linda K.',
      rating: 5,
      text: 'Called them for an emergency repair after storm damage and they came out the same day. Fantastic service and very reasonably priced compared to other quotes we received.',
      date: 'September 2023',
    },
  ],

  seo: {
    title: 'S. Tomic Roofing Ltd | Roofers in Birmingham',
    description: 'Expert roofers in Birmingham with 16 years experience. Roof repairs, installations & maintenance. 4.9* rated. Free quotes. Call +44 7521 528930 today.',
    canonicalUrl: 'https://preview-s-tomic-roofing-ltd-roofers-birmingham.vercel.app',
  },
}

export default siteData

// CSS custom properties injected by site_generator.py
// These override :root variables in index.css at runtime
export const siteTheme = {
  '--color-primary':  '#1B2D45',
  '--color-accent':   '#E85D26',
  '--color-bg':       '#FAFAF8',
  '--color-text':     '#1A1A1A',
  '--color-muted':    '#6B7280',
  '--color-border':   '#E5E5E5',
  '--font-heading':   "'Instrument Serif', Georgia, serif",
  '--font-body':      "'DM Sans', system-ui, sans-serif",
}
